build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.8.3
  amd64: ghcr.io/hassio-addons/debian-base:7.8.3

labels:
  org.opencontainers.image.title: "Claude Home"
  org.opencontainers.image.description: "AI-powered terminal interface with Claude Code CLI"
  org.opencontainers.image.source: "https://github.com/evandepol/hassio-addons"
  org.opencontainers.image.licenses: "MIT"