build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.8.3
  amd64: ghcr.io/hassio-addons/debian-base:7.8.3

labels:
  org.opencontainers.image.title: "OpenAI Watchdog"
  org.opencontainers.image.description: "Intelligent Home Assistant monitoring with continuous OpenAI analysis"
  org.opencontainers.image.source: "https://github.com/cabinlab/hassio-addons"
  org.opencontainers.image.licenses: "MIT"