build_from:
  aarch64: ghcr.io/hassio-addons/base:16.0.1
  amd64: ghcr.io/hassio-addons/base:16.0.1

labels:
  org.opencontainers.image.title: "OpenAI Watchdog"
  org.opencontainers.image.description: "Intelligent Home Assistant monitoring with continuous OpenAI analysis"
  org.opencontainers.image.source: "https://github.com/evandepol/hassio-addons"
  org.opencontainers.image.licenses: "MIT"