build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19

labels:
  org.opencontainers.image.title: "OpenAI Watchdog"
  org.opencontainers.image.description: "Intelligent Home Assistant monitoring with continuous OpenAI analysis"
  org.opencontainers.image.source: "https://github.com/evandepol/hassio-addons"
  org.opencontainers.image.licenses: "MIT"