build_from:
  aarch64: "ghcr.io/hassio-addons/base:16.0.1"
  amd64: "ghcr.io/hassio-addons/base:16.0.1"

labels:
  org.opencontainers.image.title: "Claude Watchdog"
  org.opencontainers.image.description: "Intelligent Home Assistant monitoring with continuous Claude analysis"
  org.opencontainers.image.source: "https://github.com/evandepol/hassio-addons"
  org.opencontainers.image.licenses: "MIT"

args:
  TEMPIO_VERSION: "2021.09.0"